sudo: required
services: [docker]

script:
  - docker run -v $(pwd):$(pwd) -w $(pwd) snapcore/snapcraft sh -c "apt update && snapcraft"
  - sudo apt install --yes snapd
  - sudo snap install *.snap --dangerous
